baseURL = "https://rhys.streefland.co.uk/"
languageCode = "en-gb"
title = "Rhys Streefland"
theme = "hugo-coder"
defaultcontentlanguage = "en"
publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Rhys Streefland"
    info = "Software Engineer | Runner"
    description = "Rhys Streefland's personal website"
    keywords = "developer,rhys,streefland,software,engineer,blog"
    avatarurl = "rhys.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidefooter = false
    hidecredits = true
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/rstreefland/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/rstreefland/"
[[params.social]]
    name = "Strava"
    icon = "fab fa-strava fa-2x"
    weight = 3
    url = "https://www.strava.com/athletes/26301930"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 4
    url = "https://www.instagram.com/rhysstreefland/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
